"""
Scaffold Tool — generate new CLI tool skeletons from template.

The model can use this to create project-specific CLI tools
that inherit the security framework and structured output patterns.
"""

import re
from pathlib import Path
from typing import Any

from nexus.cli.security import validate_path
from nexus.cli.utils import (
    OutputFormat, Status, emit, make_result,
)


_TOOL_TEMPLATE = '''\
"""
{description}

Auto-generated by bs-cli scaffold. Inherits security.py validators.
"""

# SECURITY: This tool must:
# - Never use shell=True in subprocess calls
# - Never use eval() or exec()
# - Validate all path inputs via security.validate_path()
# - Validate all URL inputs via security.validate_url()
# - Emit structured output via utils.emit()

from pathlib import Path
from typing import Any

import click

from nexus.cli.utils import (
    OutputFormat, Status, emit, make_result,
)
from nexus.cli.security import validate_path, validate_url


def run_{fn_name}(
    output_format: str = "json",
    project_dir: str = ".",
    **kwargs,
) -> None:
    """Run the {name} tool."""
    fmt = OutputFormat(output_format)
    proj_path = Path(project_dir).resolve()

    # TODO: Implement tool logic here

    result = make_result("{name}", Status.INFO, "{name} executed successfully")
    result["details"] = {{
        "project_dir": str(proj_path),
    }}

    emit(result, fmt)


@click.command()
@click.option("--format", "output_format", type=click.Choice(["json", "human", "yaml"]), default="human")
@click.option("--project-dir", default=".", help="Project directory.")
def cli(output_format: str, project_dir: str) -> None:
    """Run the project-local {name} tool."""
    run_{fn_name}(output_format=output_format, project_dir=project_dir)


if __name__ == "__main__":
    cli()
'''


def _sanitize_name(name: str) -> str:
    """Validate a portable, collision-resistant tool name."""
    if not re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,62}[A-Za-z0-9])?", name):
        raise ValueError(
            f"Invalid tool name: '{name}'. Use 1-64 letters, numbers, or single hyphens."
        )
    if "--" in name:
        raise ValueError(f"Invalid tool name: '{name}'. Consecutive hyphens are not allowed.")
    return name.lower()


def _name_to_fn(name: str) -> str:
    """Convert hyphenated name to Python function name."""
    return name.replace("-", "_")


def run_scaffold(
    name: str,
    description: str = "",
    output_format: str = "json",
    project_dir: str = ".",
) -> None:
    """Generate a tracked, project-local CLI tool skeleton."""
    fmt = OutputFormat(output_format)

    try:
        clean_name = _sanitize_name(name)
    except ValueError as e:
        result = make_result("scaffold", Status.FAIL, str(e))
        emit(result, fmt)
        return

    fn_name = _name_to_fn(clean_name)

    if not description:
        description = f"{clean_name} — custom CLI tool (auto-scaffolded)"

    project_root = Path(project_dir).resolve()
    if not project_root.is_dir():
        emit(make_result(
            "scaffold", Status.FAIL, f"Project directory does not exist: {project_root}"
        ), fmt)
        return

    try:
        tools_dir = validate_path("tools/nexus", project_root)
        tool_path = validate_path(f"tools/nexus/{fn_name}.py", project_root)
    except ValueError as exc:
        emit(make_result("scaffold", Status.FAIL, str(exc)), fmt)
        return

    if tool_path.exists():
        result = make_result(
            "scaffold", Status.FAIL,
            f"Tool already exists: {tool_path.name}. Choose a different name or edit the existing file.",
        )
        emit(result, fmt)
        return

    content = _TOOL_TEMPLATE.format(
        name=clean_name,
        fn_name=fn_name,
        description=description,
    )

    tools_dir.mkdir(parents=True, exist_ok=True)
    tool_path.write_text(content, encoding="utf-8")
    relative_tool = tool_path.relative_to(project_root).as_posix()

    result = make_result("scaffold", Status.PASS, f"Tool '{clean_name}' scaffolded successfully")
    result["details"] = {
        "tool_file": relative_tool,
        "tool_name": clean_name,
        "function_name": f"run_{fn_name}",
    }
    result["next_steps"] = [
        f"1. Edit {relative_tool} to implement the tool logic",
        f"2. Test: python {relative_tool} --project-dir . --format human",
        f"3. Commit {relative_tool} with the project source",
    ]

    emit(result, fmt)
